import { Header } from '../components/Header.js'

export function About(container) {
  container.innerHTML = ''
  container.appendChild(Header())

  const main = document.createElement('main')
  main.className = 'cb-about'
  main.innerHTML = `
    <h1>About concept-book</h1>
    <p>
      <strong>concept-book</strong> is an open portal that lets any learner explore a knowledge
      domain through its <em>concept graph</em> — a directed acyclic graph (DAG) where nodes
      are concepts (primitive, concept, application) and edges are prerequisite relationships.
    </p>

    <h2>How to use it</h2>
    <ol>
      <li>Pick a domain from the home page</li>
      <li>Click any concept node in the interactive graph</li>
      <li>The left sidebar shows the ordered learning path — the exact sequence of concepts you must master first</li>
      <li>Read the concept-book section for each concept in the path</li>
    </ol>

    <h2>The founding use-case: Chinese Characters</h2>
    <p>
      Chinese characters share the same structure as chemical elements — a small set of
      elemental radicals (primitives) combine to form hundreds of compound characters.
      Learning the ~12 elementals unlocks the ability to decode characters by structure alone.
      The concept graph makes that derivation visible and navigable.
    </p>

    <h2>The content engine</h2>
    <p>
      All domain graphs and concept-book text are generated by
      <a href="https://github.com/digital-duck/SPL.py" target="_blank" rel="noopener">SPL.py</a>
      — a structured programming language for LLM-driven content generation with math verification.
      concept-book is the web-app layer that hosts and presents what SPL.py produces.
    </p>

    <h2>Open source</h2>
    <p>
      concept-book is open source under the Apache 2.0 license.
      Source and contribution guide at
      <a href="https://github.com/digital-duck/concept-book" target="_blank" rel="noopener">github.com/digital-duck/concept-book</a>.
    </p>
  `
  container.appendChild(main)
}
