import { getLocale } from '../i18n.js'
import { LANGUAGES } from '../components/LanguagePicker.js'

const LEVELS = ['intro', 'core', 'college', 'research']

const MODELS = [
  { value: '', label: '— default —' },
  { value: 'gemma3', label: 'gemma3 (Ollama)' },
  { value: 'gemma4', label: 'gemma4 (Ollama)' },
  { value: 'sonnet', label: 'sonnet (Claude)' },
  { value: 'haiku', label: 'haiku (Claude)' },
  { value: 'opus', label: 'opus (Claude)' },
]

function parseLevelLang(file) {
  const m = file.match(/output\/([^.]+)\.([^/]+)\//)
  return m ? { level: m[1], lang: m[2] } : { level: 'college', lang: 'en' }
}

function conceptFilename(file) {
  return file.replace(/^.*\//, '')
}

function buildUrl(domain, file, level, lang, model) {
  const fname = conceptFilename(file)
  const modelPart = model ? `${model}/` : ''
  return `${import.meta.env.BASE_URL}domains/${domain}/output/${level}.${lang}/${modelPart}html/${fname}`
}

async function _checkExists(url) {
  try {
    const res = await fetch(url)
    if (!res.ok) return false
    const text = await res.text()
    return text.includes('spl-credit') || text.includes('Generated by')
  } catch (_) { return false }
}

function _notFoundHtml(fname, model, lang, level) {
  const conceptName = decodeURIComponent(fname).replace(/^concept_/, '').replace(/_/g, ' ').replace(/\.html$/, '')
  const modelLabel = model || 'default'
  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;padding:48px 40px;color:#374151;background:#fafafa;min-height:100vh">
    <h2 style="color:#1e3a5f;margin:0 0 16px;font-size:1.3rem">Content Not Available</h2>
    <p style="margin:0 0 12px;font-size:0.9rem;color:#6b7280">No page exists for this combination:</p>
    <div style="background:#fff;border:1px solid #e0e3e8;border-radius:8px;padding:16px 20px;margin-bottom:24px;display:inline-block">
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Model:</span><span style="color:#2563eb">${modelLabel}</span></div>
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Level:</span><span style="color:#2563eb">${level}</span></div>
      <div><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Language:</span><span style="color:#2563eb">${lang}</span></div>
    </div>
    <p style="color:#6b7280;font-size:0.88rem;line-height:1.6">Please generate the concept book for <strong style="color:#1e3a5f">${conceptName}</strong> first via the Concept-Graph page.</p>
  </body></html>`
}

async function loadFrame(frame, url, state) {
  const exists = await _checkExists(url)
  if (exists) {
    frame.src = url
  } else {
    frame.removeAttribute('src')
    frame.srcdoc = _notFoundHtml(url.replace(/.*\/html\//, ''), state.model, state.lang, state.level)
  }
}

// ── DOM helpers ───────────────────────────────────────────────────────────────

function makeSelect(options, current, cls) {
  const sel = document.createElement('select')
  if (cls) sel.className = cls
  options.forEach(({ value, label }) => {
    const opt = document.createElement('option')
    opt.value = value
    opt.textContent = label
    if (value === current) opt.selected = true
    sel.appendChild(opt)
  })
  return sel
}

// Order: Model → Level → Language
function makeControlRow(label, state, onChange) {
  const row = document.createElement('div')
  row.className = 'cb-book-pane__controls'

  if (label) {
    const lbl = document.createElement('span')
    lbl.className = 'cb-book-pane__label'
    lbl.textContent = label
    row.appendChild(lbl)
  }

  const modelSel = makeSelect(MODELS, state.model, 'cb-book-pane__select')
  modelSel.title = 'Model'
  modelSel.addEventListener('change', () => onChange('model', modelSel.value))
  row.appendChild(modelSel)

  const levelSel = makeSelect(
    LEVELS.map(v => ({ value: v, label: v.charAt(0).toUpperCase() + v.slice(1) })),
    state.level, 'cb-book-pane__select'
  )
  levelSel.title = 'Level'
  levelSel.addEventListener('change', () => onChange('level', levelSel.value))
  row.appendChild(levelSel)

  const langSel = makeSelect(
    LANGUAGES.map(l => ({ value: l.code, label: l.label })),
    state.lang, 'cb-book-pane__select'
  )
  langSel.title = 'Language'
  langSel.addEventListener('change', () => onChange('lang', langSel.value))
  row.appendChild(langSel)

  return row
}

// ── Sidebar population ────────────────────────────────────────────────────────

// Extracts nav.toc from an iframe and recreates it in a parent sidebar element.
function populateTocSidebar(sidebar, leftFrame, { compareChecked, onCompareToggle, onConceptClick }) {
  try {
    const doc = leftFrame.contentDocument
    const nav = doc?.querySelector('nav.toc')
    if (!nav) return

    sidebar.innerHTML = ''

    // Compare checkbox
    const compareWrap = document.createElement('div')
    compareWrap.style.cssText = 'margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid rgba(255,255,255,0.15)'
    const compareLabel = document.createElement('label')
    compareLabel.style.cssText = 'display:flex;align-items:center;gap:8px;cursor:pointer;font-family:system-ui,sans-serif;font-size:0.85rem;color:#e8f0fe;font-weight:600'
    const chk = document.createElement('input')
    chk.type = 'checkbox'
    chk.checked = compareChecked
    chk.style.cssText = 'width:14px;height:14px;cursor:pointer;accent-color:#60a5fa'
    chk.addEventListener('change', () => onCompareToggle(chk.checked))
    compareLabel.appendChild(chk)
    compareLabel.appendChild(document.createTextNode('Compare'))
    compareWrap.appendChild(compareLabel)
    sidebar.appendChild(compareWrap)

    // Back link
    const navBack = nav.querySelector('.back')
    if (navBack) {
      const back = document.createElement('a')
      back.textContent = navBack.textContent
      back.href = navBack.getAttribute('href') || '#/'
      back.style.cssText = 'color:#a8c8f0;margin-bottom:20px;display:block;font-family:system-ui,sans-serif;font-size:.85rem;text-decoration:none'
      back.addEventListener('mouseover', () => { back.style.color = '#fff' })
      back.addEventListener('mouseout', () => { back.style.color = '#a8c8f0' })
      sidebar.appendChild(back)
    }

    const heading = document.createElement('div')
    heading.style.cssText = 'font-size:.75rem;letter-spacing:.1em;text-transform:uppercase;color:#90b4e8;margin-bottom:14px;font-family:system-ui,sans-serif;font-weight:700'
    heading.textContent = 'Contents'
    sidebar.appendChild(heading)

    const navOl = nav.querySelector('ol')
    if (navOl) {
      const ol = document.createElement('ol')
      ol.style.cssText = 'list-style:decimal inside;padding:0;margin:0;flex:1'
      navOl.querySelectorAll('li').forEach(li => {
        const a = li.querySelector('a')
        if (!a) return
        const isTarget = li.classList.contains('toc-target')
        const newLi = document.createElement('li')
        newLi.style.cssText = `margin-bottom:7px;font-size:.85rem;line-height:1.4;font-family:system-ui,sans-serif${isTarget ? ';font-weight:700' : ''}`
        const newA = document.createElement('a')
        newA.textContent = a.textContent
        newA.href = '#'
        newA.style.cssText = `text-decoration:none;color:${isTarget ? '#fff' : '#a8c8f0'}`
        newA.addEventListener('mouseover', () => { newA.style.color = '#fff' })
        newA.addEventListener('mouseout', () => { newA.style.color = isTarget ? '#fff' : '#a8c8f0' })
        newA.addEventListener('click', e => { e.preventDefault(); onConceptClick(a.getAttribute('href')) })
        newLi.appendChild(newA)
        ol.appendChild(newLi)
      })
      sidebar.appendChild(ol)
    }

    const credit = nav.querySelector('.spl-credit')
    if (credit) {
      const div = document.createElement('div')
      div.style.cssText = 'margin-top:auto;padding-top:14px;border-top:1px solid rgba(255,255,255,0.15);font-size:11px;color:#90b4e8;font-family:system-ui,sans-serif'
      div.textContent = 'Generated by SPL'
      sidebar.appendChild(div)
    }
  } catch (_) {}
}

function hideTocInFrame(frame) {
  try {
    const doc = frame.contentDocument
    if (!doc) return
    const style = doc.createElement('style')
    style.textContent = 'nav.toc { display: none !important; } .page { grid-template-columns: 1fr !important; }'
    doc.head.appendChild(style)
  } catch (_) {}
}

function makeTocSidebarEl() {
  const el = document.createElement('nav')
  el.style.cssText = [
    'width:260px', 'flex-shrink:0',
    'background:#1e3a5f', 'color:#e8f0fe',
    'padding:24px 16px',
    'display:flex', 'flex-direction:column',
    'overflow-y:auto',
    'font-family:system-ui,sans-serif',
    'border-right:1px solid rgba(255,255,255,0.12)',
  ].join(';')
  el.innerHTML = '<div style="color:#90b4e8;font-size:12px">Loading…</div>'
  return el
}

// ── Page ──────────────────────────────────────────────────────────────────────

export function BookPage(container, params) {
  const { domain, file: initialFile } = params
  if (!domain || !initialFile) {
    container.innerHTML = '<p style="padding:40px;color:#dc2626">Invalid book URL — missing domain or file.</p>'
    return
  }

  const parsed = parseLevelLang(initialFile)
  let compareMode = false
  let currentFile = initialFile

  const p1 = { level: parsed.level, lang: parsed.lang, model: '' }
  const p2 = { level: parsed.level, lang: parsed.lang, model: '' }

  function render() {
    container.innerHTML = ''
    container.className = 'cb-book-page'
    compareMode ? renderCompare() : renderSingle()
  }

  // ── Single mode ─────────────────────────────────────────────────────────
  // Layout: [260px dark sidebar | [controls bar + iframe] ]

  function renderSingle() {
    const wrap = document.createElement('div')
    wrap.style.cssText = 'display:flex;flex:1;overflow:hidden'
    container.appendChild(wrap)

    // Left sidebar (extracted from iframe's nav.toc on load)
    const tocSidebar = makeTocSidebarEl()
    wrap.appendChild(tocSidebar)

    // Right column: thin controls bar at top + full-height iframe below
    const rightCol = document.createElement('div')
    rightCol.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0'
    wrap.appendChild(rightCol)

    const controlsBar = makeControlRow(null, p1, (key, val) => {
      p1[key] = val
      reload()
    })
    rightCol.appendChild(controlsBar)

    const frame = document.createElement('iframe')
    frame.style.cssText = 'flex:1;width:100%;border:none;display:block'
    rightCol.appendChild(frame)

    let isSrcdoc = false

    frame.addEventListener('load', () => {
      if (isSrcdoc) return
      try {
        const href = frame.contentWindow?.location?.href
        if (href && !href.startsWith('about:')) {
          const fname = decodeURIComponent(href.replace(/.*\/html\//, ''))
          if (fname && !fname.includes('://') && fname !== conceptFilename(currentFile)) {
            currentFile = currentFile.replace(/[^/]+\.html$/, fname)
          }
        }
      } catch (_) {}
      hideTocInFrame(frame)
      populateTocSidebar(tocSidebar, frame, {
        compareChecked: false,
        onCompareToggle: checked => { compareMode = checked; render() },
        onConceptClick: href => {
          if (!href) return
          currentFile = currentFile.replace(/[^/]+\.html$/, href)
          reload()
        },
      })
    })

    function reload() {
      const url = buildUrl(domain, currentFile, p1.level, p1.lang, p1.model)
      _checkExists(url).then(exists => {
        if (exists) { isSrcdoc = false; frame.src = url }
        else { isSrcdoc = true; frame.removeAttribute('src'); frame.srcdoc = _notFoundHtml(conceptFilename(currentFile), p1.model, p1.lang, p1.level) }
      })
    }

    reload()
  }

  // ── Compare mode ────────────────────────────────────────────────────────

  function renderCompare() {
    const wrap = document.createElement('div')
    wrap.style.cssText = 'display:flex;flex:1;overflow:hidden'
    container.appendChild(wrap)

    // Shared TOC sidebar
    const tocSidebar = makeTocSidebarEl()
    wrap.appendChild(tocSidebar)

    // Panes container
    const panesWrap = document.createElement('div')
    panesWrap.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0'
    wrap.appendChild(panesWrap)

    // Controls row (Pane A | Pane B)
    const controlsRow = document.createElement('div')
    controlsRow.style.cssText = 'display:flex;flex-shrink:0'
    panesWrap.appendChild(controlsRow)

    const ctrl1 = makeControlRow('Pane A', p1, (key, val) => { p1[key] = val; reloadLeft() })
    ctrl1.style.flex = '1'
    controlsRow.appendChild(ctrl1)

    const divider = document.createElement('div')
    divider.style.cssText = 'width:2px;background:#e0e3e8;flex-shrink:0'
    controlsRow.appendChild(divider)

    const ctrl2 = makeControlRow('Pane B', p2, (key, val) => { p2[key] = val; reloadRight() })
    ctrl2.style.flex = '1'
    controlsRow.appendChild(ctrl2)

    // Frames row
    const framesRow = document.createElement('div')
    framesRow.style.cssText = 'flex:1;display:flex;overflow:hidden'
    panesWrap.appendChild(framesRow)

    const leftFrame = document.createElement('iframe')
    leftFrame.style.cssText = 'flex:1;border:none;display:block;min-width:0'
    framesRow.appendChild(leftFrame)

    const frameSep = document.createElement('div')
    frameSep.style.cssText = 'width:2px;background:#e0e3e8;flex-shrink:0'
    framesRow.appendChild(frameSep)

    const rightFrame = document.createElement('iframe')
    rightFrame.style.cssText = 'flex:1;border:none;display:block;min-width:0'
    framesRow.appendChild(rightFrame)

    function onConceptClick(href) {
      if (!href) return
      currentFile = currentFile.replace(/[^/]+\.html$/, href)
      reloadLeft()
      reloadRight()
    }

    leftFrame.addEventListener('load', () => {
      try {
        const href = leftFrame.contentWindow?.location?.href
        if (href && !href.startsWith('about:')) {
          const fname = decodeURIComponent(href.replace(/.*\/html\//, ''))
          if (fname && !fname.includes('://') && fname !== conceptFilename(currentFile)) {
            currentFile = currentFile.replace(/[^/]+\.html$/, fname)
          }
        }
      } catch (_) {}
      hideTocInFrame(leftFrame)
      populateTocSidebar(tocSidebar, leftFrame, {
        compareChecked: true,
        onCompareToggle: checked => { compareMode = checked; render() },
        onConceptClick,
      })
    })

    rightFrame.addEventListener('load', () => { hideTocInFrame(rightFrame) })

    function reloadLeft() { loadFrame(leftFrame, buildUrl(domain, currentFile, p1.level, p1.lang, p1.model), p1) }
    function reloadRight() { loadFrame(rightFrame, buildUrl(domain, currentFile, p2.level, p2.lang, p2.model), p2) }

    reloadLeft()
    reloadRight()
  }

  render()
}
