import { getLocale } from '../i18n.js'
import { LANGUAGES } from '../components/LanguagePicker.js'

const LEVELS = ['intro', 'core', 'college', 'research']

const MODELS = [
  { value: '', label: '— default —' },
  { value: 'gemma3', label: 'gemma3 (Ollama)' },
  { value: 'gemma4', label: 'gemma4 (Ollama)' },
  { value: 'sonnet', label: 'sonnet (Claude)' },
  { value: 'haiku', label: 'haiku (Claude)' },
  { value: 'opus', label: 'opus (Claude)' },
]

function parseLevelLang(file) {
  const m = file.match(/output\/([^.]+)\.([^/]+)\//)
  return m ? { level: m[1], lang: m[2] } : { level: 'college', lang: 'en' }
}

function parseModel(file) {
  // Matches output/{level}.{lang}/{model}/html/ — returns model name or ''
  const m = file.match(/output\/[^/]+\/([^/]+)\/html\//)
  return m ? m[1] : ''
}

function conceptFilename(file) {
  return file.replace(/^.*\//, '')
}

function conceptFromFile(file) {
  return decodeURIComponent(conceptFilename(file).replace(/^concept_/, '').replace(/\.html$/, ''))
}

function buildUrl(domain, file, level, lang, model) {
  const fname = conceptFilename(file)
  const modelPart = model ? `${model}/` : ''
  return `${import.meta.env.BASE_URL}domains/${domain}/output/${level}.${lang}/${modelPart}html/${fname}`
}

async function _checkExists(url) {
  try {
    const res = await fetch(url)
    if (!res.ok) return false
    const text = await res.text()
    return text.includes('spl-credit') || text.includes('Generated by')
  } catch (_) { return false }
}

function _notFoundHtml(fname, model, lang, level) {
  const conceptName = decodeURIComponent(fname).replace(/^concept_/, '').replace(/_/g, ' ').replace(/\.html$/, '')
  const modelLabel = model || 'default'
  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;padding:48px 40px;color:#374151;background:#fafafa;min-height:100vh">
    <h2 style="color:#1e3a5f;margin:0 0 16px;font-size:1.3rem">Content Not Available</h2>
    <p style="margin:0 0 12px;font-size:0.9rem;color:#6b7280">No page exists for this combination:</p>
    <div style="background:#fff;border:1px solid #e0e3e8;border-radius:8px;padding:16px 20px;margin-bottom:24px;display:inline-block">
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Model:</span><span style="color:#2563eb">${modelLabel}</span></div>
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Level:</span><span style="color:#2563eb">${level}</span></div>
      <div><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Language:</span><span style="color:#2563eb">${lang}</span></div>
    </div>
    <p style="color:#6b7280;font-size:0.88rem;line-height:1.6">Please generate the concept book for <strong style="color:#1e3a5f">${conceptName}</strong> first via the Concept-Graph page.</p>
  </body></html>`
}

async function loadFrame(frame, url, state, onContentStatus) {
  const exists = await _checkExists(url)
  if (onContentStatus) onContentStatus(exists)
  if (exists) {
    frame.src = url
  } else {
    frame.removeAttribute('src')
    frame.srcdoc = _notFoundHtml(url.replace(/.*\/html\//, ''), state.model, state.lang, state.level)
  }
}

// ── Markdown renderer (for PANE C) ───────────────────────────────────────────

function _mdToHtml(md) {
  const esc = md.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return esc
    .replace(/^## (.+)$/gm, '</p><h3 style="color:#1e3a5f;margin:20px 0 8px;font-size:1rem;font-weight:700">$1</h3><p>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\n\n/g, '</p><p style="margin:0 0 12px">')
    .replace(/\n/g, ' ')
    .replace(/^/, '<p style="margin:0 0 12px">')
    .replace(/$/, '</p>')
    .replace(/<p[^>]*><\/p>/g, '')
    .replace(/<p[^>]*>(<h3)/g, '$1')
    .replace(/(<\/h3>)<\/p>/g, '$1')
}

// ── DOM helpers ───────────────────────────────────────────────────────────────

function makeSelect(options, current, cls) {
  const sel = document.createElement('select')
  if (cls) sel.className = cls
  options.forEach(({ value, label }) => {
    const opt = document.createElement('option')
    opt.value = value
    opt.textContent = label
    if (value === current) opt.selected = true
    sel.appendChild(opt)
  })
  return sel
}

function makeControlRow(label, state, onChange) {
  const row = document.createElement('div')
  row.className = 'cb-book-pane__controls'
  if (label) {
    const lbl = document.createElement('span')
    lbl.className = 'cb-book-pane__label'
    lbl.textContent = label
    row.appendChild(lbl)
  }
  const modelSel = makeSelect(MODELS, state.model, 'cb-book-pane__select')
  modelSel.title = 'Model'
  modelSel.addEventListener('change', () => onChange('model', modelSel.value))
  row.appendChild(modelSel)

  const levelSel = makeSelect(
    LEVELS.map(v => ({ value: v, label: v.charAt(0).toUpperCase() + v.slice(1) })),
    state.level, 'cb-book-pane__select'
  )
  levelSel.title = 'Level'
  levelSel.addEventListener('change', () => onChange('level', levelSel.value))
  row.appendChild(levelSel)

  const langSel = makeSelect(
    LANGUAGES.map(l => ({ value: l.code, label: l.label })),
    state.lang, 'cb-book-pane__select'
  )
  langSel.title = 'Language'
  langSel.addEventListener('change', () => onChange('lang', langSel.value))
  row.appendChild(langSel)

  return row
}

// ── Drag-to-resize splitter ───────────────────────────────────────────────────

function makeDragSplitter(getWrapper, onSplitChange) {
  const handle = document.createElement('div')
  handle.style.cssText = 'height:5px;background:#d1d5db;cursor:row-resize;flex-shrink:0;display:flex;align-items:center;justify-content:center;transition:background 0.15s'

  const grip = document.createElement('div')
  grip.style.cssText = 'width:40px;height:3px;border-radius:2px;background:#9ca3af;pointer-events:none'
  handle.appendChild(grip)

  let dragging = false
  handle.addEventListener('mouseenter', () => { if (!dragging) handle.style.background = '#bfdbfe' })
  handle.addEventListener('mouseleave', () => { if (!dragging) handle.style.background = '#d1d5db' })

  handle.addEventListener('mousedown', e => {
    e.preventDefault()
    dragging = true
    handle.style.background = '#93c5fd'

    // Transparent overlay covering the entire viewport (including iframes) so
    // mousemove/mouseup are received by the parent document even when the
    // cursor drifts into an iframe's browsing context.
    const overlay = document.createElement('div')
    overlay.style.cssText = 'position:fixed;inset:0;z-index:9999;cursor:row-resize'
    document.body.appendChild(overlay)
    document.body.style.userSelect = 'none'

    const onMove = e => {
      const wrapper = getWrapper()
      if (!wrapper) return
      const rect = wrapper.getBoundingClientRect()
      const pct = Math.min(80, Math.max(20, (e.clientY - rect.top) / rect.height * 100))
      onSplitChange(pct)
    }

    const onUp = () => {
      dragging = false
      handle.style.background = '#d1d5db'
      document.body.removeChild(overlay)
      document.body.style.userSelect = ''
      document.removeEventListener('mousemove', onMove)
      document.removeEventListener('mouseup', onUp)
    }

    document.addEventListener('mousemove', onMove)
    document.addEventListener('mouseup', onUp)
  })

  return handle
}

// ── Sidebar population ────────────────────────────────────────────────────────

function populateTocSidebar(sidebar, leftFrame, {
  compareChecked,
  compareBtnEnabled,
  skipCacheChecked,
  onCompareToggle,
  onSkipCacheToggle,
  onCompareActivate,
  onConceptClick,
}) {
  // Always clear and render Compare controls first — even when the left frame
  // has placeholder content (no nav.toc), the Compare checkbox/button must
  // remain visible and functional.
  sidebar.innerHTML = ''

  const compareWrap = document.createElement('div')
  compareWrap.style.cssText = 'margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid rgba(255,255,255,0.15)'

  const compareLabel = document.createElement('label')
  compareLabel.style.cssText = 'display:flex;align-items:center;gap:8px;cursor:pointer;font-family:system-ui,sans-serif;font-size:0.85rem;color:#e8f0fe;font-weight:600;margin-bottom:8px'
  const chk = document.createElement('input')
  chk.type = 'checkbox'
  chk.checked = compareChecked
  chk.style.cssText = 'width:14px;height:14px;cursor:pointer;accent-color:#60a5fa'
  chk.addEventListener('change', () => onCompareToggle(chk.checked))
  compareLabel.appendChild(chk)
  compareLabel.appendChild(document.createTextNode('Compare'))
  compareWrap.appendChild(compareLabel)

  if (compareChecked) {
    // Row: [↻ fresh checkbox] [Compare ▶ button]
    const row = document.createElement('div')
    row.style.cssText = 'display:flex;align-items:center;gap:6px'

    const skipLabel = document.createElement('label')
    skipLabel.style.cssText = 'display:flex;align-items:center;gap:3px;cursor:pointer;flex-shrink:0;font-family:system-ui,sans-serif;font-size:0.75rem;color:#90b4e8;white-space:nowrap'
    skipLabel.title = 'Skip cache — always run a fresh comparison'
    const skipChk = document.createElement('input')
    skipChk.type = 'checkbox'
    skipChk.checked = skipCacheChecked
    skipChk.style.cssText = 'width:12px;height:12px;cursor:pointer;accent-color:#60a5fa;flex-shrink:0'
    skipChk.addEventListener('change', () => onSkipCacheToggle(skipChk.checked))
    skipLabel.appendChild(skipChk)
    skipLabel.appendChild(document.createTextNode('↻ fresh'))
    row.appendChild(skipLabel)

    const btn = document.createElement('button')
    btn.textContent = 'Compare ▶'
    btn.disabled = !compareBtnEnabled
    btn.style.cssText = [
      'flex:1;padding:6px 10px;font-size:0.8rem;font-weight:600',
      'border-radius:6px;border:none;font-family:system-ui,sans-serif;transition:opacity 0.15s',
      compareBtnEnabled
        ? 'background:#3b82f6;color:#fff;cursor:pointer'
        : 'background:#374151;color:#6b7280;cursor:not-allowed;opacity:0.6',
    ].join(';')
    btn.title = compareBtnEnabled
      ? 'Generate AI comparison of both sections in PANE C'
      : 'Both panes need content before comparing'
    btn.addEventListener('click', () => { if (!btn.disabled) onCompareActivate() })
    row.appendChild(btn)

    compareWrap.appendChild(row)
  }

  sidebar.appendChild(compareWrap)

  // TOC section — only available when the left frame has real concept content.
  try {
    const doc = leftFrame.contentDocument
    const nav = doc?.querySelector('nav.toc')
    if (!nav) return

    const navBack = nav.querySelector('.back')
    if (navBack) {
      const back = document.createElement('a')
      back.textContent = navBack.textContent
      back.href = navBack.getAttribute('href') || '#/'
      back.style.cssText = 'color:#a8c8f0;margin-bottom:20px;display:block;font-family:system-ui,sans-serif;font-size:.85rem;text-decoration:none'
      back.addEventListener('mouseover', () => { back.style.color = '#fff' })
      back.addEventListener('mouseout', () => { back.style.color = '#a8c8f0' })
      sidebar.appendChild(back)
    }

    const heading = document.createElement('div')
    heading.style.cssText = 'font-size:.75rem;letter-spacing:.1em;text-transform:uppercase;color:#90b4e8;margin-bottom:14px;font-family:system-ui,sans-serif;font-weight:700'
    heading.textContent = 'Contents'
    sidebar.appendChild(heading)

    const navOl = nav.querySelector('ol')
    if (navOl) {
      const ol = document.createElement('ol')
      ol.style.cssText = 'list-style:decimal inside;padding:0;margin:0;flex:1'
      navOl.querySelectorAll('li').forEach(li => {
        const a = li.querySelector('a')
        if (!a) return
        const isTarget = li.classList.contains('toc-target')
        const newLi = document.createElement('li')
        newLi.style.cssText = `margin-bottom:7px;font-size:.85rem;line-height:1.4;font-family:system-ui,sans-serif${isTarget ? ';font-weight:700' : ''}`
        const newA = document.createElement('a')
        newA.textContent = a.textContent
        newA.href = '#'
        newA.style.cssText = `text-decoration:none;color:${isTarget ? '#fff' : '#a8c8f0'}`
        newA.addEventListener('mouseover', () => { newA.style.color = '#fff' })
        newA.addEventListener('mouseout', () => { newA.style.color = isTarget ? '#fff' : '#a8c8f0' })
        newA.addEventListener('click', e => { e.preventDefault(); onConceptClick(a.getAttribute('href')) })
        newLi.appendChild(newA)
        ol.appendChild(newLi)
      })
      sidebar.appendChild(ol)
    }

    const credit = nav.querySelector('.spl-credit')
    if (credit) {
      const div = document.createElement('div')
      div.style.cssText = 'margin-top:auto;padding-top:14px;border-top:1px solid rgba(255,255,255,0.15);font-size:11px;color:#90b4e8;font-family:system-ui,sans-serif'
      div.textContent = 'Generated by SPL'
      sidebar.appendChild(div)
    }
  } catch (_) {}
}

function hideTocInFrame(frame) {
  try {
    const doc = frame.contentDocument
    if (!doc) return
    const style = doc.createElement('style')
    style.textContent = 'nav.toc { display: none !important; } .page { grid-template-columns: 1fr !important; }'
    doc.head.appendChild(style)
  } catch (_) {}
}

function makeTocSidebarEl() {
  const el = document.createElement('nav')
  el.style.cssText = [
    'width:260px', 'flex-shrink:0',
    'background:#1e3a5f', 'color:#e8f0fe',
    'padding:24px 16px',
    'display:flex', 'flex-direction:column',
    'overflow-y:auto',
    'font-family:system-ui,sans-serif',
    'border-right:1px solid rgba(255,255,255,0.12)',
  ].join(';')
  el.innerHTML = '<div style="color:#90b4e8;font-size:12px">Loading…</div>'
  return el
}

// ── PANE C ────────────────────────────────────────────────────────────────────

function makePaneCEl() {
  const el = document.createElement('div')
  el.setAttribute('data-pane-c', '1')
  el.style.cssText = [
    'flex:1', 'overflow-y:auto',
    'background:#f8fafc',
    'padding:24px 32px',
    'font-family:system-ui,sans-serif',
    'font-size:0.9rem', 'line-height:1.7', 'color:#374151',
  ].join(';')
  el.innerHTML = '<div style="color:#9ca3af;font-size:0.85rem">Click <strong>Compare ▶</strong> to generate an AI comparison of the two sections above.</div>'
  return el
}

function startCompare(domain, currentFile, p1, p2, paneCEl, skipCache) {
  const concept = conceptFromFile(currentFile)
  const modelA = p1.model || 'default'
  const modelB = p2.model || 'default'

  const params = new URLSearchParams({
    domain, concept,
    level_a: p1.level, lang_a: p1.lang, model_a: p1.model,
    level_b: p2.level, lang_b: p2.lang, model_b: p2.model,
    skip_cache: skipCache ? '1' : '0',
  })

  paneCEl.innerHTML = `
    <div style="display:flex;align-items:center;gap:12px;color:#6b7280;font-size:0.88rem">
      <div style="width:18px;height:18px;border:2px solid #e0e3e8;border-top-color:#3b82f6;border-radius:50%;animation:cb-spin 0.8s linear infinite;flex-shrink:0"></div>
      Comparing <strong style="color:#1e3a5f;margin:0 3px">${modelA}</strong> vs <strong style="color:#1e3a5f;margin:0 3px">${modelB}</strong>…
    </div>
    <style>@keyframes cb-spin{to{transform:rotate(360deg)}}</style>`

  const t0 = performance.now()
  const source = new EventSource(`/api/compare?${params}`)

  source.addEventListener('compare_done', e => {
    source.close()
    const elapsed = ((performance.now() - t0) / 1000).toFixed(1)
    const { comparison, from_cache } = JSON.parse(e.data)
    const cacheTag = from_cache
      ? '<span style="font-size:0.7rem;padding:2px 6px;border-radius:10px;background:#d1fae5;color:#065f46;font-weight:600;flex-shrink:0">cached</span>'
      : ''
    paneCEl.innerHTML = `
      <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:18px;padding-bottom:12px;border-bottom:1px solid #e0e3e8">
        <span style="font-size:0.7rem;letter-spacing:.1em;text-transform:uppercase;color:#6b7280;font-weight:700">PANE C — Comparison</span>
        <span style="font-size:0.8rem;color:#374151">
          <strong style="color:#2563eb">${modelA}</strong> (${p1.level}/${p1.lang})
          <span style="color:#9ca3af;margin:0 6px">vs</span>
          <strong style="color:#2563eb">${modelB}</strong> (${p2.level}/${p2.lang})
        </span>
        ${cacheTag}
        <span style="font-size:0.72rem;color:#9ca3af;margin-left:auto">${elapsed}s</span>
      </div>
      <div style="max-width:820px">${_mdToHtml(comparison)}</div>`
  })

  source.addEventListener('compare_error', e => {
    source.close()
    const { message } = JSON.parse(e.data)
    paneCEl.innerHTML = `<p style="color:#dc2626;font-size:0.88rem"><strong>Comparison failed:</strong> ${message}</p>`
  })

  source.onerror = () => {
    source.close()
    paneCEl.innerHTML = `<p style="color:#dc2626;font-size:0.88rem">Connection to comparison service lost.</p>`
  }

  return source
}

// ── Page ──────────────────────────────────────────────────────────────────────

export function BookPage(container, params) {
  const { domain, file: initialFile } = params
  if (!domain || !initialFile) {
    container.innerHTML = '<p style="padding:40px;color:#dc2626">Invalid book URL — missing domain or file.</p>'
    return
  }

  const parsed = parseLevelLang(initialFile)
  let compareMode = false
  let compareTriggered = false
  let paneAHasContent = false
  let paneBHasContent = false
  let skipCache = false
  let splitPct = 60
  let currentFile = initialFile
  let compareSource = null

  // The resizeWrapper reference is kept so the drag handler can measure it
  let resizeWrapperEl = null
  // The top section reference so we can update its flex-basis on drag
  let topSectionEl = null

  const p1 = { level: parsed.level, lang: parsed.lang, model: parseModel(initialFile) }
  const p2 = { level: parsed.level, lang: parsed.lang, model: '' }

  function cancelCompare() {
    if (compareSource) { compareSource.close(); compareSource = null }
  }

  // Finds PANE C in current DOM (works across re-renders)
  function getPaneC() {
    return container.querySelector('[data-pane-c]')
  }

  function render() {
    cancelCompare()
    container.innerHTML = ''
    container.className = 'cb-book-page'
    resizeWrapperEl = null
    topSectionEl = null
    compareMode ? renderCompare() : renderSingle()
  }

  // ── Single mode ──────────────────────────────────────────────────────────

  function renderSingle() {
    const wrap = document.createElement('div')
    wrap.style.cssText = 'display:flex;flex:1;overflow:hidden'
    container.appendChild(wrap)

    const tocSidebar = makeTocSidebarEl()
    wrap.appendChild(tocSidebar)

    const rightCol = document.createElement('div')
    rightCol.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0'
    wrap.appendChild(rightCol)

    rightCol.appendChild(makeControlRow(null, p1, (key, val) => { p1[key] = val; reload() }))

    const frame = document.createElement('iframe')
    frame.style.cssText = 'flex:1;width:100%;border:none;display:block'
    rightCol.appendChild(frame)

    let isSrcdoc = false

    frame.addEventListener('load', () => {
      if (isSrcdoc) return
      try {
        const href = frame.contentWindow?.location?.href
        if (href && !href.startsWith('about:')) {
          const fname = decodeURIComponent(href.replace(/.*\/html\//, ''))
          if (fname && !fname.includes('://') && fname !== conceptFilename(currentFile)) {
            currentFile = currentFile.replace(/[^/]+\.html$/, fname)
          }
        }
      } catch (_) {}
      hideTocInFrame(frame)
      populateTocSidebar(tocSidebar, frame, {
        compareChecked: false,
        compareBtnEnabled: false,
        skipCacheChecked: false,
        onCompareToggle: checked => { compareMode = checked; render() },
        onSkipCacheToggle: () => {},
        onCompareActivate: () => {},
        onConceptClick: href => {
          if (!href) return
          if (href.startsWith('#')) {
            try { frame.contentDocument?.querySelector(href)?.scrollIntoView({ behavior: 'smooth' }) } catch (_) {}
            return
          }
          currentFile = currentFile.replace(/[^/]+\.html$/, href)
          reload()
        },
      })
    })

    function reload() {
      const url = buildUrl(domain, currentFile, p1.level, p1.lang, p1.model)
      _checkExists(url).then(exists => {
        isSrcdoc = !exists
        if (exists) { frame.src = url }
        else { frame.removeAttribute('src'); frame.srcdoc = _notFoundHtml(conceptFilename(currentFile), p1.model, p1.lang, p1.level) }
      })
    }

    reload()
  }

  // ── Compare mode ─────────────────────────────────────────────────────────

  function renderCompare() {
    const wrap = document.createElement('div')
    wrap.style.cssText = 'display:flex;flex:1;overflow:hidden'
    container.appendChild(wrap)

    const tocSidebar = makeTocSidebarEl()
    wrap.appendChild(tocSidebar)

    const mainArea = document.createElement('div')
    mainArea.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0'
    wrap.appendChild(mainArea)

    // Controls row
    const controlsRow = document.createElement('div')
    controlsRow.style.cssText = 'display:flex;flex-shrink:0'
    mainArea.appendChild(controlsRow)

    const ctrl1 = makeControlRow('Pane A', p1, (key, val) => { p1[key] = val; reloadLeft() })
    ctrl1.style.flex = '1'
    controlsRow.appendChild(ctrl1)

    const ctrlDivider = document.createElement('div')
    ctrlDivider.style.cssText = 'width:2px;background:#e0e3e8;flex-shrink:0'
    controlsRow.appendChild(ctrlDivider)

    const ctrl2 = makeControlRow('Pane B', p2, (key, val) => { p2[key] = val; reloadRight() })
    ctrl2.style.flex = '1'
    controlsRow.appendChild(ctrl2)

    // Resizable wrapper: top (frames) + optional drag handle + PANE C
    const resizeWrapper = document.createElement('div')
    resizeWrapper.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden'
    mainArea.appendChild(resizeWrapper)
    resizeWrapperEl = resizeWrapper

    // Top section: PANE A | PANE B frames
    const topSection = document.createElement('div')
    topSection.style.cssText = `flex:0 0 ${compareTriggered ? splitPct + '%' : '100%'};display:flex;overflow:hidden;min-height:0`
    resizeWrapper.appendChild(topSection)
    topSectionEl = topSection

    const leftFrame = document.createElement('iframe')
    leftFrame.style.cssText = 'flex:1;border:none;display:block;min-width:0'
    topSection.appendChild(leftFrame)

    topSection.appendChild((() => {
      const d = document.createElement('div')
      d.style.cssText = 'width:2px;background:#e0e3e8;flex-shrink:0'
      return d
    })())

    const rightFrame = document.createElement('iframe')
    rightFrame.style.cssText = 'flex:1;border:none;display:block;min-width:0'
    topSection.appendChild(rightFrame)

    // Drag handle + PANE C — only after Compare button is clicked
    if (compareTriggered) {
      const dragHandle = makeDragSplitter(
        () => resizeWrapperEl,
        pct => {
          splitPct = pct
          if (topSectionEl) topSectionEl.style.flex = `0 0 ${pct}%`
        }
      )
      // Visually separate PANE C with a label strip
      const paneCHeader = document.createElement('div')
      paneCHeader.style.cssText = 'flex-shrink:0;background:#1e3a5f;color:#90b4e8;padding:4px 16px;font-size:0.7rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;display:flex;align-items:center;gap:8px'
      paneCHeader.innerHTML = '<span>PANE C — AI Comparison</span>'

      resizeWrapper.appendChild(dragHandle)
      resizeWrapper.appendChild(paneCHeader)
      resizeWrapper.appendChild(makePaneCEl())
    }

    // Sidebar refresh — rebuilds the Compare button state
    function refreshSidebar() {
      populateTocSidebar(tocSidebar, leftFrame, {
        compareChecked: true,
        compareBtnEnabled: paneAHasContent && paneBHasContent,
        skipCacheChecked: skipCache,
        onCompareToggle: checked => { compareMode = checked; render() },
        onSkipCacheToggle: val => { skipCache = val },
        onCompareActivate: () => {
          if (!compareTriggered) {
            compareTriggered = true
            render()
            // render() is synchronous; PANE C is now in the DOM
          }
          const pC = getPaneC()
          if (pC) {
            cancelCompare()
            compareSource = startCompare(domain, currentFile, p1, p2, pC, skipCache)
          }
        },
        onConceptClick: href => {
          if (!href) return
          if (href.startsWith('#')) {
            try { leftFrame.contentDocument?.querySelector(href)?.scrollIntoView({ behavior: 'smooth' }) } catch (_) {}
            return
          }
          currentFile = currentFile.replace(/[^/]+\.html$/, href)
          reloadLeft()
          reloadRight()
        },
      })
    }

    leftFrame.addEventListener('load', () => {
      try {
        const href = leftFrame.contentWindow?.location?.href
        if (href && !href.startsWith('about:')) {
          const fname = decodeURIComponent(href.replace(/.*\/html\//, ''))
          if (fname && !fname.includes('://') && fname !== conceptFilename(currentFile)) {
            currentFile = currentFile.replace(/[^/]+\.html$/, fname)
          }
        }
      } catch (_) {}
      hideTocInFrame(leftFrame)
      refreshSidebar()
    })

    rightFrame.addEventListener('load', () => { hideTocInFrame(rightFrame) })

    function reloadLeft() {
      loadFrame(leftFrame, buildUrl(domain, currentFile, p1.level, p1.lang, p1.model), p1, hasContent => {
        paneAHasContent = hasContent
        refreshSidebar()
      })
    }

    function reloadRight() {
      loadFrame(rightFrame, buildUrl(domain, currentFile, p2.level, p2.lang, p2.model), p2, hasContent => {
        paneBHasContent = hasContent
        refreshSidebar()
      })
    }

    reloadLeft()
    reloadRight()
  }

  render()
}
